### ISSUE TITLE
Developer Roll Call

### ISSUE THREAD

**Issue by LawJolla** [LawJolla/su2j-filesharing#1]
Thank you for dropping in!

We are designing an application to help [Step Up to Justice](http://www.stepuptojustice.org/) ("SU2J") manage their file sharing between attorneys and clients.  Currently, they have an ad-hoc solution where attorneys may share through Sharepoint and other means.  This application streamlines SU2J workflows so they can serve even more clients.

The bounds of this application are not yet defined.  We will be working with the SU2J team to define the project's scope in the coming weeks. 

Our goal is to create a supportive, cooperative, collaborative, and inclusive developer community and experience where developers of any experience can learn, share, and contribute to a real world, non-trivial application that will significantly enhance the lives of many who desperately need legal assistance.  We will also be mindful of everyone's time and outside responsibilities.  This should be a fun experience -- not one that adds stress.

To the extent possible, we'd like to compartmentalize sections into mini, self-contained apps where a developer can take ownership and share on future resumes.  We will keep this project open source so it can be referenced and used as an example of work product.

### Development Stack

This is web based so it'll use web tech (HTML, CSS, Javascript).  Given the sensitive nature of the data, I believe punting authentication and authorization to a provider, like Auth0 or Okta, is needed.  I'm also extremely bullish on TailwindCSS for a CSS framework.

Other than those few choices, I want to make the rest of the stack collaborative.  This could be Rails.  It could be Node/GraphQL.  It could be Rust (though let's not 🤣).

If this sounds like something that interests you, please reply below!  Copy the introduction template below and tell us about you!  We'll see the responses over the next week and go from there.

### Introduction

**Name**
Dennis Walsh

**Location**
Tucson, AZ

**Experience With (Languages, frameworks, services, etc. )...**
React, Node, Typescript, GraphQL, Postgres, Auth0, PHP, Elixir, Prisma, AWS, Heroku, Netlify, Stripe, TailwindCSS/TailwindUI

**Preferred Stack**
Typescript, React, Node, GraphQL, Auth0, TailwindUI (I purchased a license)

**Want to learn, tech**
I'd be interested to learn Svelte if the project went that direction.  I'm interested to learn how to implement rules based access control and this granular of a level.  And I need to get better with and learn more about integration testing.

**Want to learn, professionally**
I normally work alone, so I'm interested in the collaborative aspect and managing a team.

**Area preference, e.g. backend, frontend, CSS, database, etc**
No preference

**Comment by pattiereaves** [comment]
🙋‍♀️ hey! I'm still interested in helping. Here's my life story

### Name
Pattie Reaves

### Location
Tucson, AZ

### Experience with
React/Redux, Node, PHP (WordPress/Laravel), many flavors of managing stylesheets (scss/postss/css modules/styled components), strong accessibility background

### Preferred stack
React and Node

### Want to learn, tech
Typescript, GraphQL, super game for anything that I would never use at work to be honest. Tailwind sounds interesting.

### Want to learn, professionally
More about my Pima County community

### Area preference
Front-end, but I'm not intimidated by back-end or dev ops

**Comment by agracey** [comment]
I'm in! 

### Name

Andrew Gracey

### Location

Bend, OR

### Experience with

React/Redux, Node, PHP, GraphQL/Apollo, Clojure(script), Java, K8s

### Preferred Stack

React (without hooks?) / Node / Typescript? / Graphql 

### Want to Learn, tech

anything

### Want to learn, professionally

anything

### Area preference

I'm pretty full stack with more experience in FE, Devops, and architecture

**Comment by Most-Basic33** [comment]
Introducing Me!

**Name**
Bishop Walker

**Location**
Phoenix AZ till the end of the year than Washington DC

**Experience with**
React/Redux, Node, HTML-5, Postgres, Socket.io, AWS S3, Java (limited)
 

**Want to Learn, tech**
React/Redux, Authentication, File.IO 

**Want to learn, professionally**
Java Spring-Boot, Java Micro-Services, Data Structures, 

**Area preference**
I like to challenge myself, but in a way where the goal is attainable. I can do a little of a lot but I'm not good at much. I'm really good at taking specs and project requirements and then completing whatever task I was assigned.

**Comment by LawJolla** [comment]
@agracey and @Most-Basic33 thrilled to have you!  Out of curiosity, how did you find this project?  (Pattie and I know each other from local meet ups)

I'm meeting with one more developer early next week that I hope to bring on and then we will get this party started.

To start the house keeping, does anyone have a preferred communication method or should we all be cliche with a Slack channel? 🤣

**Comment by Most-Basic33** [comment]
believe we met on Linkedin, and slack is fine
 @Bishop Walker is my name on slack

**Comment by Dameon1** [comment]
Introduction
Name
Dameon mendoza

Location
Tucson, AZ

Experience With (Languages, frameworks, services, etc. )...
React, Node, Typescript, GraphQL, Postgres, Auth0, Prisma, AWS, Heroku, alphbet soup

Preferred Stack
 React, Node, Mongo, Express

Want to learn, tech
Open to anything

Want to learn, professionally


Area preference, e.g. backend, frontend, CSS, database, etc
No preference

**Comment by LawJolla** [comment]
Hi @Most-Basic33 @pattiereaves @agracey and @Dameon1 ,

We have our team together!   Huge thanks to everyone.  Here's where we stand..

1.  Stack
It looks like React is the overwhelming choice so React it is.  There also seems to be a strong bent towards Typescript and GraphQL.  I think Typescript makes a ton of sense for this project.  And I'm a GraphQL fan boy but it looks like there's interest unrelated to my hopes and dreams :).

So React and Typescript, and probably GraphQL/Node.  Does that work?  More decisions to follow.

2.  Prototyping
I am a Framer Pro member.  It's an amazing tool built on React (and a lot of the code can copy and paste into the app!).  And because I've already paid for it, it'll be free for us to use.  I've sent an invitation to everyone but @Most-Basic33 (Bishop, if you can get me your email, I can get the invite out).

If you know Figma, XD, or Sketch, you should pick up Framer very quickly.

3.  What now
  a.  I'll get SU2J to set up a Slack channel for us.  Invites to follow.
  b.  We can ping them on Slack and drill down on the requirements.  I'll post what I know about it so far on Slack and we can take it from there.

4.  What's next.
We need to drill down with the client on what this app is and isn't.  In my opinion, we should build out the prototype, send builds to the client, and let them tell us if we are hitting the features and functionality they need.  We could be on prototyping for quite a while.  (Measure twice, cut once).

My question is who's interested in working on the prototyping?

**Comment by Most-Basic33** [comment]
Walkerbishop333@gmail.com
